language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kalanchan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kalanchan/react-test npm test -- --coverage

after_success:
  - docker build -t kalanchan/multi-client ./client
  - docker build -t kalanchan/multi-nginx ./nginx
  - docker build -t kalanchan/multi-server ./server
  - docker build -t kalanchan/multi-worker ./worker
  # login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker hub
  - docker push kalanchan/multi-client
  - docker push kalanchan/multi-nginx
  - docker push kalanchan/multi-server
  - docker push kalanchan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-662094392100"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
