language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kalan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kalan/react-test npm test -- --coverage

after_success:
  - docker build -t kalan/multi-client ./client
  - docker build -t kalan/multi-nginx ./nginx
  - docker build -t kalan/multi-server ./server
  - docker build -t kalan/multi-worker ./worker
  # login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker hub
  - docker push kalan/multi-client
  - docker push kalan/multi-nginx
  - docker push kalan/multi-server
  - docker push kalan/multi-worker
